FROM ubuntu:16.04
MAINTAINER sixzeroo60@gmail.com

COPY sources.list /etc/apt/sources.list

COPY pip.conf /etc/pip.conf

RUN apt-get update && apt-get -y install cron \
    && apt-get -y install python3 python3-pip \
    && ln -s /usr/bin/pip3 /usr/bin/pip
